server:
  port: 8888
  context-path: /daejong


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ganjiDB?characterEncoding=utf-8&useSSL=false
    username: root
    password: daejong

  freemarker:
      #关闭缓存
      cache: false
      request-context-attribute: request
      #模板加载的位置
      template-loader-path: classpath:/templates
      #前缀
      suffix: .html
      #后缀
      prefix: /

mybatis:
  #实体类所做包, 省去了再mapper.xml中的type前
  type-aliases-package: com.daejong.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml

